init_args:
  _target_: models.generators.llm.LLM
  model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
  max_new_tokens: 128
  max_length: 2048
  # quantization: "int4"
  batch_size: 8
  use_attr: false
  use_cad: false
  no_context: false
  attr_ds_name: null
  num_attr_samples: 100
  neuron_selection_mode: first
  random_seed: 42