init_args:
  _target_: models.generators.llm.LLM
  model_name: "Ori/llama-2-13b-peft-nq-retrobust"
  max_new_tokens: 128
  max_length: 2048
  batch_size: 4
  use_attr: false
  use_cad: false
  no_context: false
